CREATE DATABASE LOAN_DEFAULT;
USE LOAN_DEFAULT;
SELECT*FROM LOAN_DEFAULT_CLEANED LIMIT 10;
-- DISPLAY ALL RECORDS FROM THE LOAN_DEFAULT TABLE
SELECT*FROM LOAN_DEFAULT_CLEANED;

-- DISPLAY ONLY LOANID,AGE,INCOME AND LOANAMOUNT
SELECT LOANID,AGE,INCOME,LOANAMOUNT 
FROM LOAN_DEFAULT_CLEANED;

-- FIND CUSTOMERS WHOSE INCOME IS GREATER THAN 80,000
SELECT*FROM LOAN_DEFAULT_CLEANED
WHERE INCOME>80000;

-- DISPLAY CUSTOMERS WHOSE CREDIT SCORE IS BETWEEN 650 AND 750
SELECT*FROM LOAN_DEFAULT_CLEANED
WHERE CREDITSCORE BETWEEN 650 AND 750;

-- SHOW THE TOP10 CUSTOMERS WITH THE HIGHEST LOAN AMOUNT
SELECT LOANID,LOANAMOUNT FROM LOAN_DEFAULT_CLEANED
ORDER BY LOANAMOUNT DESC
LIMIT 10;

-- DISPLAY THE 10 CUSTOMERS WITH HIGHEST INCOME
SELECT LOANID,INCOME FROM LOAN_DEFAULT_CLEANED
ORDER BY INCOME DESC
LIMIT 10;

-- DISPLAY THE 5 CUSOMERS WITH LOWEST INTEREST RATE
SELECT LOANID,INTERESTRATE FROM LOAN_DEFAULT_CLEANED
ORDER BY INTERESTRATE ASC
LIMIT 5;

-- DISPLAY ALL CUSTOMERS ORDER BY CREDIT SCORE 
SELECT*FROM LOAN_DEFAULT_CLEANED
ORDER BY CREDITSCORE DESC;

-- FIND THE TOTAL NUMBER OF CUSTOMERS
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM LOAN_DEFAULT_CLEANED;

-- FIND THE AVERAGE LOAN AMOUNT
SELECT ROUND(AVG(LOANAMOUNT),2)AS AVERAGE_LOAN_AMOUNT
FROM LOAN_DEFAULT_CLEANED;

-- FIND THE MAXIMUM AND MINIMUM CREDIT SCORE
SELECT MAX(CREDITSCORE)AS MAXIMUM_CREDIT_SCORE,
MIN(CREDITSCORE)AS MINIMUM_CREDIT_SCORE
FROM LOAN_DEFAULT_CLEANED;

-- FIND THE TOTAL LOAN AMOUNT ISSUED BY THE BANK
SELECT SUM(LOANAMOUNT)AS TOTAL_LOAN_AMOUNT
FROM LOAN_DEFAULT_CLEANED;

-- COUNT CUSTOMERS BASED ON EDUCATION
SELECT EDUCATION,COUNT(*) AS TOTAL_CUSTOMERS
FROM LOAN_DEFAULT_CLEANED
GROUP BY EDUCATION;

-- AVERAGE INCOME BY EMPLOYMENT TYPE
SELECT EMPLOYMENTTYPE,
ROUND(AVG(INCOME),2)AS AVERAGE_INCOME
FROM LOAN_DEFAULT_CLEANED
GROUP BY EMPLOYMENTTYPE;

-- AVERAGE CREDIT SCORE BY MARITAL STATUS
SELECT MARITALSTATUS,
ROUND(AVG(CREDITSCORE),2)AS AVERAGE_CREDIT_SCORE
FROM LOAN_DEFAULT_CLEANED
GROUP BY MARITALSTATUS;

-- TOTAL AMOUNT LOAN BY LOAN PURPOSE
SELECT LOANPURPOSE,
SUM(LOANAMOUNT)AS TOTAL_LOAN_AMOUNT
FROM LOAN_DEFAULT_CLEANED
GROUP BY LOANPURPOSE;

-- EMPLOYMENT TYPES WITH AVERAGE INCOME ABOVE 70000
SELECT EMPLOYMENTTYPE,
AVG(INCOME)AS AVERAGE_INCOME
FROM LOAN_DEFAULT_CLEANED
GROUP BY EMPLOYMENTTYPE
HAVING AVG(INCOME)>70000;

-- CATEGORISE CUSTOMERS BASED ON INCOME
SELECT LOANID,INCOME,
CASE
WHEN INCOME>=80000 THEN 'HIGH_INCOME'
WHEN INCOME>=50000 THEN 'MEDIUM_INCOME'
ELSE 'LOW_INCOME'
END AS INCOME_CATEGORY
FROM LOAN_DEFAULT_CLEANED;

-- CREATE CREDIT SCORE CATEGORY
SELECT LOANID,CREDITSCORE,
CASE
WHEN CREDITSCORE>=750 THEN 'EXCELLENT'
WHEN CREDITSCORE>=650 THEN'GOOD'
ELSE 'POOR'
END AS CREDIT_CATEGORY
FROM LOAN_DEFAULT_CLEANED;

-- CUSTOMERS EARNING MORE THAN AVERAGE INCOME
SELECT * FROM LOAN_DEFAULT_CLEANED WHERE INCOME>
(SELECT AVG(INCOME) FROM LOAN_DEFAULT_CLEANED);

-- CUSTOMERS HAVING LOAN AMOUNT GREATER THAN AVERAGE
SELECT* FROM LOAN_DEFAULT_CLEANED
WHERE LOANAMOUNT>(SELECT AVG(LOANAMOUNT) FROM LOAN_DEFAULT_CLEANED);

-- CUSTOMER HAVING HIGHEST CREDIT SCORE
SELECT * FROM LOAN_DEFAULT_CLEANED
WHERE CREDITSCORE=(SELECT MAX(CREDITSCORE) FROM LOAN_DEFAULT_CLEANED);

-- RANK CUSTOMERS BASED ON INCOME
SELECT LOANID,INCOME,
RANK()OVER(ORDER BY INCOME DESC)AS INCOME_RANK
FROM LOAN_DEFAULT_CLEANED;

-- PREVIOUS CUTOMER LOAN AMOUNT
SELECT LOANID,LOANAMOUNT,
LAG(LOANAMOUNT)OVER(ORDER BY LOANAMOUNT)AS PREVIOUS_LOAN
FROM LOAN_DEFAULT_CLEANED;

-- DIVIDE CUSTOMERS INTO 4 GROUPS BASED ON CREDIT SCORE
SELECT LOANID,CREDITSCORE,
NTILE(4) OVER(ORDER BY CREDITSCORE DESC)AS CREDIT_QUARTILE
FROM LOAN_DEFAULT_CLEANED;

-- CUSTOMERS WHOSE INCOME IS GREATER THAN AVERAGE INCOME
WITH HIGH_INCOME AS (SELECT*FROM LOAN_DEFAULT_CLEANED
WHERE INCOME>(SELECT AVG(INCOME) FROM LOAN_DEFAULT_CLEANED))
SELECT * FROM HIGH_INCOME;

















